### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by jesieleo** [jgillick/IconsetCropper#1]
Hello, I am very interested in your library, but it does not work properly during use, could you please help me to solve it?
```
PayloadTooLargeError: request entity too large
    at readStream (D:\BaiduNetdiskDownload\SVGIconsetCropper-main\node_modules\raw-body\index.js:156:17)
    at getRawBody (D:\BaiduNetdiskDownload\SVGIconsetCropper-main\node_modules\raw-body\index.js:109:12)
    at read (D:\BaiduNetdiskDownload\SVGIconsetCropper-main\node_modules\body-parser\lib\read.js:79:3)
    at urlencodedParser (D:\BaiduNetdiskDownload\SVGIconsetCropper-main\node_modules\body-parser\lib\types\urlencoded.js:116:5)
    at Layer.handle [as handle_request] (D:\BaiduNetdiskDownload\SVGIconsetCropper-main\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BaiduNetdiskDownload\SVGIconsetCropper-main\node_modules\express\lib\router\index.js:328:13)
    at D:\BaiduNetdiskDownload\SVGIconsetCropper-main\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BaiduNetdiskDownload\SVGIconsetCropper-main\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BaiduNetdiskDownload\SVGIconsetCropper-main\node_modules\express\lib\router\index.js:280:10)
    at jsonParser (D:\BaiduNetdiskDownload\SVGIconsetCropper-main\node_modules\body-parser\lib\types\json.js:119:7)
```

![hello](https://user-images.githubusercontent.com/90036937/225018796-d4073d41-66e0-4d74-9f70-8c2e50fa9a91.svg)

**Comment by jesieleo** [comment]
Probably because my SVG image is a bit big

**Comment by jgillick** [comment]
Please help me understand how to reproduce the error you're seeing. Are you trying to crop a set if SVG icons or a single SVG file? If you're trying to crop a set of icons, can you include the URL to where you got the set from? What's the command you're using?

If you're trying to crop a single SVG image, try  [svgcrop](https://svgcrop.com/).

**Comment by jgillick** [comment]
If you're trying to crop a single SVG image, try  [svgcrop](https://svgcrop.com/).

**Comment by jgillick** [comment]
I also just updated the server to handle larger files (up to 10MB), so that might also help you.

**Comment by jesieleo** [comment]
Thank you very much for the awsome software ! 
I just entered the default code you said described, which worked well with files smaller than 100kb.
